version: 2

models:
  - name: stg_pubmed_citations
    description: "Parsed Medline Citations from Bronze layer"
    columns:
      - name: source_id
        description: "The PMID (PubMed ID)"
        tests:
          - not_null
      - name: coreason_id
        description: "Deterministic UUIDv5 based on PMID"
        tests:
          - unique
          - not_null
      - name: title
        tests:
          - not_null
      - name: ingestion_ts
        tests:
          - not_null
