version: 2

models:
  - name: stg_pubmed_baseline
    description: "Staged view of the Pubmed Baseline (historical) data."
    columns:
      - name: pmid
        description: "The PubMed ID (unique identifier)."
        tests:
          - not_null
      - name: doi
        description: "The Digital Object Identifier (DOI) of the article, extracted from ELocationID."

  - name: stg_pubmed_updates
    description: "Staged view of the Pubmed Daily Updates."
    columns:
      - name: pmid
        description: "The PubMed ID."
        tests:
          - not_null
      - name: doi
        description: "The Digital Object Identifier (DOI) of the article."

  - name: stg_pubmed_citations
    description: "Unified staging view combining Baseline and Updates. 1:1 view of parsed JSON."
    columns:
      - name: pmid
        description: "The PubMed ID."
        tests:
          - not_null
      - name: operation
        description: "The operation type: 'upsert' or 'delete'."
        tests:
          - not_null
          - accepted_values:
              values: ['upsert', 'delete']
      - name: file_name
        description: "Source filename."

  - name: int_pubmed_deduped
    description: "Deduplicated view combining Baseline and Updates. Uses window functions to pick the latest version."
    columns:
      - name: source_id
        description: "The PMID."
        tests:
          - unique
          - not_null
      - name: coreason_id
        description: "Deterministic UUID v5 generated from the PMID."
        tests:
          - unique
          - not_null
      - name: doi
        description: "The DOI of the article."

  - name: gold_pubmed_authors
    description: "Flattened view of authors with their ranks."
    columns:
      - name: coreason_id
        description: "The Coreason ID of the article."
        tests:
          - not_null
      - name: source_id
        description: "The PMID."
        tests:
          - not_null
      - name: author_rank
        description: "The rank of the author in the author list (1-based)."
        tests:
          - not_null
      - name: author_id
        description: "Deterministic UUID for the author."
        tests:
          - not_null
    tests:
      - unique:
          column_name: "source_id || '-' || author_rank::text"

  - name: gold_pubmed_knowledge
    description: "The final Gold layer table partitioned by year."
    columns:
      - name: source_id
        description: "The PMID."
        tests:
          - unique
          - not_null
      - name: doi
        description: "The DOI of the article."
