name: 'coreason_etl_pubmedabstracts'
version: '1.0.0'
config-version: 2

profile: 'coreason_etl_pubmedabstracts'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

on-run-start:
  - "create extension if not exists \"uuid-ossp\""

models:
  coreason_etl_pubmedabstracts:
    # Staging reads from Bronze
    staging:
      +materialized: view
    # Intermediate writes to Silver
    intermediate:
      +materialized: view
      +schema: silver
    # Marts write to Gold
    marts:
      +materialized: table
      +schema: gold
