
name: 'coreason_etl_pubmedabstracts'
version: '1.0.0'
config-version: 2

profile: 'coreason_etl_pubmedabstracts'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by 'dbt clean'
  - "target"
  - "dbt_packages"

models:
  coreason_etl_pubmedabstracts:
    # Configured via Medallion Architecture
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
