coreason_etl_pubmedabstracts:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_HOST', 'localhost') }}"
      user: "{{ env_var('DBT_USER', 'postgres') }}"
      pass: "{{ env_var('DBT_PASS', 'postgres') }}"
      port: "{{ env_var('DBT_PORT', 5432) | int }}"
      dbname: "{{ env_var('DBT_DBNAME', 'postgres') }}"
      schema: "{{ env_var('DBT_SCHEMA', 'public') }}"
      threads: 4
